#!/bin/bash
set -e

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*"}

# remove old package files if they still exist (in preinst, postinst, postrm -
# see manpage for dpkg-mainscript-helper)
conffiles=(/etc/{{init.d,logrotate.d}/quagga,quagga/{debian.conf,daemons}})
for conffile in ${conffiles[*]}; do
  dpkg-maintscript-helper rm_conffile $conffile 1.1.0-1~ quagga -- "$@"
done

#DEBHELPER#
